name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag for the Docker image'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          COMMIT_SHA=${{ github.sha }}
          docker build -t stackdriver_exporter:${COMMIT_SHA} .

      - name: Save the Docker image to the workspace
        run: |
          COMMIT_SHA=${{ github.sha }}
          docker save stackdriver_exporter:${COMMIT_SHA} | gzip > stackdriver_exporter_${COMMIT_SHA}.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: stackdriver_exporter_image
          path: stackdriver_exporter_${{ github.sha }}.tar.gz

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: stackdriver_exporter_image

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Load the Docker image
        run: |
          COMMIT_SHA=${{ github.sha }}
          gunzip -c stackdriver_exporter_${COMMIT_SHA}.tar.gz | docker load

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image to Docker Hub
        run: |
          COMMIT_SHA=${{ github.sha }}
          docker tag stackdriver_exporter:${COMMIT_SHA} ${{ secrets.DOCKERHUB_USERNAME }}/stackdriver_exporter:${COMMIT_SHA}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/stackdriver_exporter:${COMMIT_SHA}

      - name: Print Docker image tag and commit SHA
        run: |
          COMMIT_SHA=${{ github.sha }}
          echo "Docker image pushed with tag: $COMMIT_SHA"
