name: Build, Push and Scan Docker Image

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag for the Docker image'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          TAG="v-${{ github.run_number }}"
          docker build -t stackdriver_exporter:${TAG} .

      - name: Save the Docker image to the workspace
        run: |
          TAG="v-${{ github.run_number }}"
          docker save stackdriver_exporter:${TAG} | gzip > stackdriver_exporter_${TAG}.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: stackdriver_exporter_image
          path: stackdriver_exporter_v-${{ github.run_number }}.tar.gz

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: stackdriver_exporter_image

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Load the Docker image
        run: |
          TAG="v-${{ github.run_number }}"
          gunzip -c stackdriver_exporter_${TAG}.tar.gz | docker load

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image to Docker Hub
        run: |
          TAG="v-${{ github.run_number }}"
          docker tag stackdriver_exporter:${TAG} ${{ secrets.DOCKERHUB_USERNAME }}/stackdriver_exporter:${TAG}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/stackdriver_exporter:${TAG}

      - name: Print Docker image tag and run number
        run: |
          TAG="v-${{ github.run_number }}"
          echo "Docker image pushed with tag: $TAG"
          
  scan:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Install Trivy (latest)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://aquasecurity.github.io/trivy-repo/deb/public.key -O - | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb/ $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Scan Docker Image with Trivy
        run: |
          TAG="v-${{ github.run_number }}"
          trivy image ${{ secrets.DOCKERHUB_USERNAME }}/stackdriver_exporter:${TAG}
